name: Docker Image CI

on:
  push:
    tags:
      - 'v*'  # Matches tags that start with 'v', e.g., v1.0.0
    branches:
      - main  # Only run on main branch

jobs:
  build-and-push:
    # Only run if both conditions are met: main branch and tag push
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Get version from Directory.Build.props
      id: get_version
      run: |
        VERSION=$(grep -oP '(?<=<Version>).*(?=</Version>)' Backend/Directory.Build.props)
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./Backend
        file: ./Backend/LoyaltyCards.API/Dockerfile
        platforms: linux/arm64,linux/amd64
        push: true
        tags: |
          ${{ secrets.DOCKER_HUB_USERNAME }}/loyaltycardsbackend:latest
          ${{ secrets.DOCKER_HUB_USERNAME }}/loyaltycardsbackend:${{ steps.get_version.outputs.VERSION }}
